/* eslint-disable */

export const warehouses = [
    { id: '1', code: 'ALM-001', name: 'Almacén Principal', description: 'Almacén central de herramientas', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '2', code: 'ALM-002', name: 'Almacén de Calibración', description: 'Almacén para herramientas en calibración', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '3', code: 'ALM-003', name: 'Almacén de Mantenimiento', description: 'Almacén para herramientas en mantenimiento', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

export const locations = [
    { id: '1', warehouseId: '1', code: 'A1', name: 'Pasillo A - Estante 1', level: '1', section: 'A', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '2', warehouseId: '1', code: 'A2', name: 'Pasillo A - Estante 2', level: '1', section: 'A', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '3', warehouseId: '1', code: 'B1', name: 'Pasillo B - Estante 1', level: '1', section: 'B', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '4', warehouseId: '2', code: 'CAL-1', name: 'Zona de Calibración 1', level: '1', section: 'CAL', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '5', warehouseId: '3', code: 'MAN-1', name: 'Zona de Mantenimiento 1', level: '1', section: 'MAN', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

export const categories = [
    { id: '1', code: 'CAT-001', name: 'Herramientas Manuales', description: 'Herramientas de uso manual', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '2', code: 'CAT-002', name: 'Herramientas Eléctricas', description: 'Herramientas que requieren energía eléctrica', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '3', code: 'CAT-003', name: 'Instrumentos de Medición', description: 'Instrumentos para mediciones de precisión', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '4', code: 'CAT-004', name: 'Equipos de Seguridad', description: 'Equipos de protección personal', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

export const subcategories = [
    { id: '1', categoryId: '1', code: 'SUB-001', name: 'Llaves', description: 'Llaves de diferentes tipos', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '2', categoryId: '1', code: 'SUB-002', name: 'Destornilladores', description: 'Destornilladores varios', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '3', categoryId: '2', code: 'SUB-003', name: 'Taladros', description: 'Taladros eléctricos', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '4', categoryId: '3', code: 'SUB-004', name: 'Calibradores', description: 'Calibradores de precisión', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
    { id: '5', categoryId: '3', code: 'SUB-005', name: 'Micrómetros', description: 'Micrómetros de precisión', active: true, createdAt: '2024-01-01', updatedAt: '2024-01-01' },
];

export const tools = [
    {
        id: '1',
        code: 'TOOL-001',
        name: 'Calibrador Vernier Digital 6"',
        description: 'Calibrador digital de alta precisión con lectura en mm y pulgadas',
        categoryId: '3',
        subcategoryId: '4',
        brand: 'Mitutoyo',
        model: 'CD-6"CSX',
        serialNumber: 'MIT-2024-001',
        partNumber: 'P/N-500-196-30',
        warehouseId: '1',
        locationId: '1',
        status: 'available',
        condition: 'excellent',
        requiresCalibration: true,
        calibrationInterval: 365,
        lastCalibrationDate: '2024-01-15',
        nextCalibrationDate: '2025-01-15',
        calibrationCertificate: 'CERT-2024-001',
        purchaseDate: '2023-06-01',
        purchasePrice: 250.00,
        supplier: 'Tools Internacional',
        warranty: '12 meses',
        warrantyExpiration: '2024-06-01',
        active: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01'
    },
    {
        id: '2',
        code: 'TOOL-002',
        name: 'Micrómetro Exterior 0-25mm',
        description: 'Micrómetro de exteriores con precisión de 0.01mm',
        categoryId: '3',
        subcategoryId: '5',
        brand: 'Starrett',
        model: 'T230XRL-25',
        serialNumber: 'STR-2024-002',
        partNumber: 'P/N-T230-25',
        warehouseId: '1',
        locationId: '1',
        status: 'in_calibration',
        condition: 'good',
        requiresCalibration: true,
        calibrationInterval: 180,
        lastCalibrationDate: '2024-06-01',
        nextCalibrationDate: '2024-12-01',
        calibrationCertificate: 'CERT-2024-025',
        purchaseDate: '2023-03-15',
        purchasePrice: 180.00,
        supplier: 'Precision Tools SA',
        active: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01'
    },
    {
        id: '3',
        code: 'TOOL-003',
        name: 'Taladro Eléctrico 1/2"',
        description: 'Taladro eléctrico reversible de 1/2 pulgada',
        categoryId: '2',
        subcategoryId: '3',
        brand: 'DeWalt',
        model: 'DWD520',
        serialNumber: 'DEW-2024-003',
        partNumber: 'P/N-DWD520',
        warehouseId: '1',
        locationId: '2',
        status: 'available',
        condition: 'good',
        requiresCalibration: false,
        purchaseDate: '2023-08-20',
        purchasePrice: 350.00,
        supplier: 'Power Tools Bolivia',
        warranty: '24 meses',
        warrantyExpiration: '2025-08-20',
        active: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01'
    },
    {
        id: '4',
        code: 'TOOL-004',
        name: 'Juego de Llaves Combinadas 8-19mm',
        description: 'Set de llaves combinadas métricas',
        categoryId: '1',
        subcategoryId: '1',
        brand: 'Stanley',
        model: 'STMT74713',
        serialNumber: 'STN-2024-004',
        warehouseId: '1',
        locationId: '3',
        status: 'in_use',
        condition: 'good',
        requiresCalibration: false,
        purchaseDate: '2023-05-10',
        purchasePrice: 75.00,
        supplier: 'Ferreteríaaeronáutica',
        active: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01'
    },
    {
        id: '5',
        code: 'TOOL-005',
        name: 'Torquímetro Digital 10-100 Nm',
        description: 'Torquímetro digital con memoria de lecturas',
        categoryId: '3',
        subcategoryId: '4',
        brand: 'Gedore',
        model: 'TORCOTRON',
        serialNumber: 'GED-2024-005',
        partNumber: 'P/N-8612-050',
        warehouseId: '2',
        locationId: '4',
        status: 'in_calibration',
        condition: 'excellent',
        requiresCalibration: true,
        calibrationInterval: 180,
        lastCalibrationDate: '2024-05-01',
        nextCalibrationDate: '2024-11-01',
        calibrationCertificate: 'CERT-2024-045',
        purchaseDate: '2023-02-14',
        purchasePrice: 890.00,
        supplier: 'Instruments Pro',
        warranty: '36 meses',
        warrantyExpiration: '2026-02-14',
        active: true,
        createdAt: '2024-01-01',
        updatedAt: '2024-01-01'
    },
];

export const inventorySummary = {
    total: 5,
    available: 2,
    inUse: 1,
    inCalibration: 2,
    inMaintenance: 0,
    quarantine: 0,
    decommissioned: 0
};
